# prevent printing garbage when attaching via Windows Terminal
set -g focus-events off
set -sg escape-time 500

setw -g mode-keys vi
set -g default-terminal "xterm-256color"
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel
bind-key -T copy-mode-vi 'Home' send -X start-of-line
bind-key -T copy-mode-vi 'End' send -X end-of-line
bind-key -T copy-mode-vi 'Escape' send -X cancel
