# prevent printing garbage when attaching via Windows Terminal
set -g focus-events off
set -sg escape-time 500

# enable activity monitoring for activity flag
setw -g monitor-activity on

# disable visual bell
setw -g visual-bell off

# vim mode
setw -g mode-keys vi
set -g default-terminal "xterm-256color"
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel
bind-key -T copy-mode-vi 'Home' send -X start-of-line
bind-key -T copy-mode-vi 'End' send -X end-of-line
bind-key -T copy-mode-vi 'Escape' send -X cancel

# quickly reload source from this file
bind r source-file /etc/tmux.conf

# copy mode colours
setw -g mode-style 'fg=black, bg=darkgrey'

# status line stuff
# general status line colours
setw -g status-style 'fg=green, bg=#303030'
setw -g status-position bottom
setw -g pane-border-style 'fg=darkgrey'
setw -g pane-active-border-style 'fg=green'
setw -g message-style 'fg=#303030, bg=green'

# update status line every second
# set status display time to slightly over 2 seconds so it doesn't immediately disappear
setw -g status-interval 1
setw -g display-time 2100

# status line left
# changes colour to yellow with an ! if there's activity in a backgrounded window
setw -g window-status-format '#{?window_activity_flag,#[fg=yellow],#[default]}#{?window_activity_flag,!,}#I:#W#{?window_zoomed_flag,+,}'
setw -g window-status-current-format '#[reverse]#I:#W#{?window_zoomed_flag,+,}'

# status line right
setw -g status-right-length 100
setw -g status-right "#[bold]#[reverse] #(whoami)@#H #[default]#[bold] %Y-%m-%d %H:%M:%S"
